apiVersion: apps/v1
kind: Deployment
metadata:
  name: rex-backend
  namespace: rex-deployment
  labels:
    app: rex-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rex-backend
  template:
    metadata:
      labels:
        app: rex-backend
    spec:
      containers:
      - name: rex-backend
        image:  raseebriyazkhan/rex-backend
        ports:
        - containerPort: 8747
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/rex-chat-app
        volumeMounts:  # Corrected indentation
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc

