apiVersion: v1
kind: Service
metadata:
  name: rex-frontend
  namespace: rex-deployment 
spec:
  selector:
    app: rex-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort
