apiVersion: apps/v1
kind: Deployment
metadata:
  name: rex-deployment
  namespace: rex-deployment
  labels:
    app: rex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rex-frontend
  template:
    metadata:
      labels:
        app: rex-frontend
    spec:
      containers:
      - name: rex-frontend
        image: raseebriyazkhan/rex-frontend:latest
        ports:
        - containerPort: 5173

